export enum Stack {
    JAVASCRIPT = "JAVASCRIPT",
    TYPESCRIPT = "TYPESCRIPT",
    JAVA = "JAVA",
    HTMLCSS = "HTMLCSS",
    BANCODEDADOS = "BANCODEDADOS",
    REACT = "REACT",
    REACTNATIVE = "REACTNATIVE",
    NODE = "NODE",
    ARDUINO = "ARDUINO",
    ANGULAR = "ANGULAR",
    VUEJS = "VUEJS",
    OUTRO = "OUTRO"
}