# Configurações para produção (AWS)
spring.datasource.url=jdbc:postgresql://SEU_RDS_ENDPOINT:5432/qcurso-api
spring.datasource.username=postgres
spring.datasource.password=senha_super_segura_aws
spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=true
server.port=5000

# Configurações de segurança
spring.security.oauth2.client.registration.google.client-id=seu-client-id
spring.security.oauth2.client.registration.google.client-secret=seu-client-secret

# Logging
logging.level.org.springframework=INFO
logging.level.br.com.uniamerica.qCurso.com=DEBUG
